fork_recipes/backend/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from recipes import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

if settings.DEBUG:
    urlpatterns = [
        path('', include('recipes.urls', namespace="recipes")),
        path('schedule/', include('schedule.urls', namespace="schedule")),
        path('shopping/', include('shopping.urls', namespace="shopping")),
        path('settings/', include('settings.urls', namespace="settings")),

                  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()
else:
    urlpatterns = [
        path('', include('recipes.urls', namespace="recipes")),
        path('schedule/', include('schedule.urls', namespace="schedule")),
        path('shopping/', include('shopping.urls', namespace="shopping")),
        path('settings/', include('settings.urls', namespace="settings")),
    ]


handler404 = views.handler404
handler500 = views.handler500

fork_recipes/recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_list, name='recipe_list'),
    path('random/', views.random_recipe, name='random_recipe'),
    path('recipe/<int:recipe_pk>/', views.recipe_detail, name='recipe_detail'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.log_out_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-password/reset', views.change_password_after_reset, name='change_password_after_reset'),

    path('saved-recipes/', views.saved_recipes, name='saved_recipes'),
    path('profile/', views.profile_view, name='profile'),
    path('toggle-favorite/<int:recipe_pk>/', views.toggle_favorite, name='toggle_favorite'),
    path('new-recipe/', views.new_recipe, name='new_recipe'),
    path('recipe/<int:recipe_pk>/edit/', views.edit_recipe, name='edit_recipe'),
    path('scrape-recipe/', views.scrape_recipe, name='scrape_recipe'),
    path('generate-recipes/', views.generate_recipe, name="generate_recipes"),
    path('recipe/<int:recipe_pk>/translate/', views.translate_recipe_view, name="translate_recipe"),
    path('recipe/<int:recipe_pk>/audio/', views.generate_audio_for_recipe, name="audio_recipe"),
    path('recipe/<int:recipe_pk>/delete', views.delete_recipe, name="delete_recipe"),
    path('settings/change-password/', views.change_password, name='change_password'),
    path('settings/delete-account/', views.delete_account, name='delete_account'),
    path("recipe/<int:recipe_pk>/print/", views.print_recipe, name="print_recipe")
]

fork_recipes/schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedule'



urlpatterns = [
    path('', views.schedule_list, name='schedule_list'),
    path('create/', views.create_schedule_meal_type, name='create_schedule'),

]

fork_recipes/schedule/models.py
TIMING_CHOICES = [
    ('Breakfast', 'Breakfast'),
    ('Lunch', 'Lunch'),
    ('Dinner', 'Dinner'),
    ('Side', 'Side'),
]

fork_recipes/schedule/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from fork_recipes.ws import api_request


@login_required
def schedule_list(request):
    date = str(datetime.datetime.now().date())

    if request.POST:
        date = request.POST.get('selected_date')
        if not date:
            date = str(datetime.datetime.now().date())

    response = api_request.request_get_schedule_of_a_day(date)

    breakfast = [x for x in response if x.timing == 'Breakfast']
    lunch = [x for x in response if x.timing == 'Lunch']
    dinner = [x for x in response if x.timing == 'Dinner']
    side = [x for x in response if x.timing == 'Side']

    breakfast = breakfast[0] if len(breakfast) > 0 else None
    lunch = lunch[0] if len(lunch) > 0 else None
    dinner = dinner[0] if len(dinner) > 0 else None
    side = side[0] if len(side) > 0 else None

    is_plan_empty = (breakfast, lunch, dinner, side) == (None, None, None, None)

    return render(request, 'schedule.html',
                  context={"breakfast": breakfast, "lunch": lunch, "dinner": dinner, "side": side, "current_selected_date": date, "is_plan_empty": is_plan_empty})


@login_required
def create_schedule_meal_type(request):
    if request.POST:
        meal_type = request.POST.get('meal_type')
        date = request.POST.get('date')
        recipe_id = request.POST.get('recipe_id')
        token = request.session.get("auth_token")

        response = api_request.request_post_schedule(date, recipe_id, meal_type, token)
        if response:
            messages.success(request, f'Recipe was added to schedule for date {date}')
        else:
            messages.error(request, f'There was an error processing the request.Please try again.')

        return redirect("recipes:recipe_detail", recipe_pk=recipe_id)

fork_recipes/schedule/templates/schedule.html
{% extends 'recipes/base.html' %}

{% block title %}Meal Planner - Fork Recipes{% endblock %}

{% block header %}Meal Planner{% endblock %}

{% block content %}
<div class="max-w-3xl mx-auto p-6 bg-white rounded-xl shadow-lg">
    <h2 class="text-2xl font-semibold text-gray-800 mb-6 text-center">Select date</h2>

    <div class="relative max-w-sm mx-auto mb-6">
        <form id="date-form" method="POST" action="/schedule/">
            {% csrf_token %}
            <input id="default-datepicker" type="date" name="selected_date" value="{{ current_selected_date }}"
                   class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full px-4 py-2"
                   placeholder="Select date">
        </form>
    </div>


    <section class="bg-white antialiased">
        <div class="max-w-screen-xl px-4 py-8 mx-auto lg:px-6 sm:py-16 lg:py-24">
            <div class="max-w-3xl mx-auto text-center">
                <h2 class="text-2xl font-extrabold leading-tight tracking-tight text-gray-900">
                    Schedule
                </h2>
            </div>


            {% if is_plan_empty %}
            <div class="text-center">
                <p class="text-base  font-semibold text-mint-700">404</p>
                <h1 class="mt-4 text-3xl font-semibold tracking-tight text-balance text-gray-600 sm:text-4xl">No plan
                    for this date</h1>
            </div>
            {% else %}
            <div class="flow-root max-w-3xl mx-auto mt-8 sm:mt-12 lg:mt-16">
                <div class="-my-4 divide-y divide-gray-200 ">
                    {% if breakfast %}
                    <div class="flex flex-col gap-2 py-4 sm:gap-6 sm:flex-row sm:items-center">
                        <p class="w-32 text-lg font-normal text-gray-500 sm:text-right  shrink-0">
                            Breakfast
                        </p>
                        <div class="flex flex-col sm:flex-row items-center sm:items-center gap-y-4 sm:gap-x-6 flex-1">
                            <!-- Image Section -->
                            <img class="h-16 w-16 flex-none rounded-full bg-gray-50 object-cover"
                                 src="{{ breakfast.recipe.image }}" alt="Recipe Image">
                            <!-- Recipe Name and Link Section -->
                            <div class="flex flex-col flex-auto text-center sm:text-left justify-center items-center sm:items-start">
                                <p class="text-sm font-bold text-gray-900">{{ breakfast.recipe.name }}</p>
                            </div>
                        </div>
                        <!-- Button Section -->
                        <div class="flex gap-4 mt-4 justify-center sm:justify-end sm:mt-0">
                            <button onclick="location.href='{% url 'recipes:recipe_detail' recipe_pk=breakfast.recipe.pk %}'"
                                    class="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-mint-600 hover:bg-mint-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-mint-500">
                                Prepare Recipe
                            </button>
                        </div>
                    </div>
                    {% else %}
                    {% endif %}
                    {% if lunch %}
                    <div class="flex flex-col gap-2 py-4 sm:gap-6 sm:flex-row sm:items-center">
                        <p class="w-32 text-lg font-normal text-gray-500 sm:text-right shrink-0">
                            Lunch
                        </p>
                        <div class="flex flex-col sm:flex-row items-center sm:items-center gap-y-4 sm:gap-x-6 flex-1">
                            <!-- Image Section -->
                            <img class="h-16 w-16 flex-none rounded-full bg-gray-50 object-cover"
                                 src="{{ lunch.recipe.image }}" alt="Recipe Image">
                            <!-- Recipe Name and Link Section -->
                            <div class="flex flex-col flex-auto text-center sm:text-left justify-center">
                                <p class="text-sm font-bold text-gray-900">{{ lunch.recipe.name }}</p>
                            </div>
                        </div>
                        <!-- Button Section -->
                        <div class="flex gap-4 mt-4 justify-center sm:justify-end sm:mt-0">
                            <button onclick="location.href='{% url 'recipes:recipe_detail' recipe_pk=lunch.recipe.pk %}'"
                                    class="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-mint-600 hover:bg-mint-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-mint-500">
                                Prepare Recipe
                            </button>
                        </div>

                    </div>
                    {% else %}
                    {% endif %}
                    {% if dinner %}
                    <div class="flex flex-col gap-2 py-4 sm:gap-6 sm:flex-row sm:items-center">
                        <p class="w-32 text-lg font-normal text-gray-500 sm:text-right  shrink-0">
                            Dinner
                        </p>
                        <div class="flex flex-col sm:flex-row items-center sm:items-center gap-y-4 sm:gap-x-6 flex-1">
                            <!-- Image Section -->
                            <img class="h-16 w-16 flex-none rounded-full bg-gray-50 object-cover"
                                 src="{{ dinner.recipe.image }}" alt="Recipe Image">
                            <!-- Recipe Name and Link Section -->
                            <div class="flex flex-col flex-auto text-center sm:text-left justify-center">
                                <p class="text-sm font-bold text-gray-900">{{ dinner.recipe.name }}</p>
                            </div>
                        </div>
                        <!-- Button Section -->
                        <div class="flex gap-4 mt-4 justify-center sm:justify-end sm:mt-0">
                            <button onclick="location.href='{% url 'recipes:recipe_detail' recipe_pk=dinner.recipe.pk %}'"
                                    class="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-mint-600 hover:bg-mint-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-mint-500">
                                Prepare Recipe
                            </button>
                        </div>
                    </div>
                    {% else %}
                    {% endif %}
                    {% if side %}
                    <div class="flex flex-col gap-2 py-4 sm:gap-6 sm:flex-row sm:items-center">
                        <p class="w-32 text-lg font-normal text-gray-500 sm:text-right  shrink-0">
                            Side
                        </p>
                        <div class="flex flex-col sm:flex-row items-center sm:items-center gap-y-4 sm:gap-x-6 flex-1">
                            <!-- Image Section -->
                            <img class="h-16 w-16 flex-none rounded-full bg-gray-50 object-cover"
                                 src="{{ side.recipe.image }}" alt="Recipe Image">
                            <!-- Recipe Name and Link Section -->
                            <div class="flex flex-col flex-auto text-center sm:text-left justify-center">
                                <p class="text-sm font-bold text-gray-900">{{ side.recipe.name }}</p>
                            </div>
                        </div>
                        <!-- Button Section -->
                        <div class="flex gap-4 mt-4 justify-center sm:justify-end sm:mt-0">
                            <button onclick="location.href='{% url 'recipes:recipe_detail' recipe_pk=side.recipe.pk %}'"
                                    class="inline-flex items-center px-6 py-3 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-mint-600 hover:bg-mint-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-mint-500">
                                Prepare Recipe
                            </button>
                        </div>

                    </div>
                    {% else %}
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
    </section>

    <form action="{% url 'recipes:scrape_recipe' %}" method="post" class="space-y-4">
        {% csrf_token %}

    </form>
</div>

{% if messages %}
<div class="fixed bottom-4 right-4">
    {% for message in messages %}
    <div class="bg-white shadow-lg rounded-lg px-4 py-3 {% if message.tags %}{{ message.tags }}{% endif %} mb-2">
        <p class="text-sm">{{ message }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const dateInput = document.getElementById("default-datepicker");

        dateInput.addEventListener("change", function () {
            document.getElementById('date-form').submit();

        });
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const dateInput = document.getElementById("default-datepicker");
        const today = new Date();
        const oneWeekAgo = new Date();
        oneWeekAgo.setDate(today.getDate() - 7);
        const formatDate = (date) => date.toISOString().split("T")[0];

        dateInput.min = formatDate(oneWeekAgo);
    });
</script>
{% endblock %}